// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolERP.Auth.Infrastructure.Persistence;

#nullable disable

namespace SchoolERP.Auth.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260521011156_Update_Auth_Matrix_2026")]
    partial class Update_Auth_Matrix_2026
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.MenuData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("CanDelete")
                        .HasColumnType("int");

                    b.Property<int>("CanEdit")
                        .HasColumnType("int");

                    b.Property<int>("CanInsert")
                        .HasColumnType("int");

                    b.Property<int>("CanView")
                        .HasColumnType("int");

                    b.Property<string>("MenuBanglaName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MenuIcon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MenuParentId")
                        .HasColumnType("int");

                    b.Property<string>("MenuTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MenuURL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuName", "MenuParentId")
                        .IsUnique();

                    b.ToTable("MenuDatas");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.RoleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("RoleDatas");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.RolesWiseMenuAssignData", b =>
                {
                    b.Property<int>("RoleDataId")
                        .HasColumnType("int");

                    b.Property<int>("MenuDataId")
                        .HasColumnType("int");

                    b.Property<int>("CanDelete")
                        .HasColumnType("int");

                    b.Property<int>("CanEdit")
                        .HasColumnType("int");

                    b.Property<int>("CanInsert")
                        .HasColumnType("int");

                    b.Property<int>("CanView")
                        .HasColumnType("int");

                    b.HasKey("RoleDataId", "MenuDataId");

                    b.ToTable("RolesWiseMenuAssignDatas");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.UserData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserBloodGroupId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserGenderId")
                        .HasColumnType("int");

                    b.Property<int>("UserMaritalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("UserMobileNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserNationality")
                        .HasColumnType("int");

                    b.Property<string>("UserPhoto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserReligionId")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("UserDatas");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.UserDataPermissionData", b =>
                {
                    b.Property<long>("UserDataId")
                        .HasColumnType("bigint");

                    b.Property<int>("LookUpId")
                        .HasColumnType("int");

                    b.Property<int>("TypeNo")
                        .HasColumnType("int");

                    b.HasKey("UserDataId", "LookUpId", "TypeNo");

                    b.ToTable("UserDataPermissionDatas");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.UserMenuPermissionData", b =>
                {
                    b.Property<long>("UserDataId")
                        .HasColumnType("bigint");

                    b.Property<int>("MenuDataId")
                        .HasColumnType("int");

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("CanDelete")
                        .HasColumnType("int");

                    b.Property<int>("CanEdit")
                        .HasColumnType("int");

                    b.Property<int>("CanInsert")
                        .HasColumnType("int");

                    b.Property<int>("CanView")
                        .HasColumnType("int");

                    b.HasKey("UserDataId", "MenuDataId");

                    b.HasIndex("MenuDataId");

                    b.ToTable("UserMenuPermissionDatas");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.UserTransactionLogData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComputerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OSName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserTransactionLogDatas");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.RolesWiseMenuAssignData", b =>
                {
                    b.HasOne("SchoolERP.Auth.Domain.Entities.RoleData", null)
                        .WithMany("DataList")
                        .HasForeignKey("RoleDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.UserDataPermissionData", b =>
                {
                    b.HasOne("SchoolERP.Auth.Domain.Entities.UserData", "UserData")
                        .WithMany()
                        .HasForeignKey("UserDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.UserMenuPermissionData", b =>
                {
                    b.HasOne("SchoolERP.Auth.Domain.Entities.MenuData", "MenuData")
                        .WithMany()
                        .HasForeignKey("MenuDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuData");
                });

            modelBuilder.Entity("SchoolERP.Auth.Domain.Entities.RoleData", b =>
                {
                    b.Navigation("DataList");
                });
#pragma warning restore 612, 618
        }
    }
}
